name: Pull Request Test

on:
  push:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run gh version
        run: |
          gh --version

      - name: Run auth login
        run: |
          gh auth login --with-token < ${{ secrets.GITHUB_TOKEN }}

      - name: Create pull request
        run: |
          gh pr create --base release --title "To Release" --body "This is PR for release branch" --assignee "@n0ts"

