name: Pull Request Test

on:
  push:
    branches:
      - main

jobs:
  pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Run gh command
        run: |
          gh --version



